version: "3"

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - HOME=/tmp
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - /Users/jiliarsilgado/Documents/big_data_training/data/chapter6:/data
      - /Users/jiliarsilgado/Documents/big_data_training/code/chapter6:/scripts

  spark-worker-1:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - /Users/jiliarsilgado/Documents/big_data_training/data/chapter6:/data
      - /Users/jiliarsilgado/Documents/big_data_training/code/chapter6:/scripts